version: '3.1'

services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: testp_db
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data